## Important Equations (for Reference)

These are straight out of Ljungqvist and Sargent.

### Eq. (8.2.2)

A feasible allocation satisfies 

\begin{align*}
\sum_{i} c_t^i(s^t) \leq \sum_{i} y_t^i(s^t)
\end{align*}

for all $t$ and for all $s^t$.

### Eq. (8.5.1)

The consumer's budget constraint is 

\begin{align*}
\sum_{t=0}^\infty \sum_{s^t} q_t^0(s^t)c_t^i(s^t) \leq \sum_{t=0}^\infty \sum_{s^t} q_t^0(s^t) y_t^i(s^t) 
\end{align*}

### Eq. (8.5.4)

\begin{align*}
\beta^t u_i' (c_t^i(s^t)) \pi_t(s^t) = \mu_i q_t^0(s^t)
\end{align*}

### Eq. (8.5.5)

\begin{align*}
\frac{u_i'(c_t^i(s^t))}{u_j'(c_t^j(s^t))} = \frac{\mu_i}{\mu_j}
\end{align*}

for all pairs of $(i,j)$.

### Eq. (8.5.6)

An equilibrium allocation solves equations (8.2.2), (8.5.1), and (8.5.5).
Note that equation (8.5.5) implies that 

\begin{align*}
c_t^i(s^t) = u_i'^{-1} \left\{ u_1' (c_t^1(s^t)) \frac{\mu_i}{\mu_1} \right\} 
\end{align*}

### Eq. (8.5.7)

Substitution (8.5.6) into Eq. (8.2.2) at equality gives 

\begin{align*}
\sum_i u_i'^{-1} \left\{ u_1' (c_t^1(s^t)) \frac{\mu_i}{\mu_1} \right\}  = \sum_i y_t^i(s^t) 
\end{align*}

## Negishi Algorithm

To compute an equilibrium, we have to determine ratios of the Lagrange multipliers, $\mu_i/\mu_1$, $i = 1,\ldots,I$, that appear in equations (8.5.6) and (8.5.7).

The following **Negishi algorithm** accomplishes this:

(1) Fix any positive value for one $\mu_i$, say $\mu_1$, throughout the algorithm.
Guess positive values for the remaining $\mu_i$'s.
Then solve equations (8.5.6) and (8.5.7) for a candidate consumption allocation $c^i$, $i = 1,\ldots,I$.

(2) Use (8.5.4) for any consumer $i$ to solve for the price system $q_t^0(s^t)$.

(3) For $i = 1,\ldots,I$, check the budget constraint (8.5.1).
For those $i$'s for which the cost of consumption exceeds the value of their endowment, raise $\mu_i$, while for those $i$'s for which the reverse inequality holds, lower $\mu_i$.

(4) Iterate to convergence on steps 1-3.

## Basic Setup

Load all necessary packages.

In [81]:
using LinearAlgebra

Specify basic model properties.

In [134]:
I = 5 # number of agents
μ = ones(I) # Lagrange multipliers for each agent
s = [1, 2] # states 
N = length(s) # total number of states 
W = zeros(N,I) # empty wage matrix 

for i in 1:N
    W[i,:] = randn(I) # Fill out wage matrix
end 

T = 2 # total number of time periods (t = 0,1,...,T)
;

Create a function that generates the set of all possible histories $s^t$ for any given $t$ for the specified model.

In [129]:
all_perm(s, t) = vec(map(collect, Iterators.product(ntuple(_ -> s, t+1)...)))

all_perm (generic function with 1 method)

Specify some more model primitives.

Specifically, set up the underlying Markov process for the state variable.

In [130]:
P0 = ones(N)/N # initial distribution
M = [0.9 0.1; 0.5 0.5] # stochastic matrix

2×2 Array{Float64,2}:
 0.9  0.1
 0.5  0.5

Create a function that returns the probability of any given history $s^t$.

In [131]:
function outcome_prob(history, P0, M)
    
# Store probability of initial state 
probability = P0[history[1]]

# Compute probability of `outcome` sequence
for i in 2:length(history)
    probability = probability * M[history[i-1], history[i]]
    end 
    
    # Return `probability` -- prob. of sequence `outcome`
    return probability
end 

outcome_prob (generic function with 1 method)

Let's make sure that our functions work.

In [132]:
history = all_perm(s, 2)

8-element Array{Array{Int64,1},1}:
 [1, 1, 1]
 [2, 1, 1]
 [1, 2, 1]
 [2, 2, 1]
 [1, 1, 2]
 [2, 1, 2]
 [1, 2, 2]
 [2, 2, 2]

In [133]:
history = all_perm(s, 2)[2]
outcome_prob(history, P0, M)

0.225

The above code is sufficient to allow us to set up any kind of state process.

## Step \#1 of the Negishi Algorithm

Guess Langrange multipliers for all agents.

Recall that $\mu_1$ (or any other $\mu_i$) must be fixed at some arbitrary value forever.

We will keep $\mu_1 = 1$.

In [136]:
μ = ones(I) # Lagrange multipliers for each agent

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

Now we must solve Eqs. (8.5.6) and (8.5.7) for a candidate consumption allocation $c^i$ for all $i$.

## Step \#2 of the Negishi Algorithm

## Step \#3 of the Negishi Algorithm